// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tevfik — https://github.com/tevfik/ceedless
//
// Mock generator: scan a header for function declarations and emit
// MOCK_DEFINE(...) stubs to stdout (or -o FILE).

package main

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

var reFuncDecl = regexp.MustCompile(
	`(?m)^\s*` +
		`((?:[A-Za-z_][A-Za-z_0-9 *]*?\s+\**))` + // return type (greedy w/ stars)
		`([A-Za-z_][A-Za-z_0-9]*)\s*\(\s*([^)]*)\s*\)\s*;`)

func cmdMock(args []string) error {
	fs := flag.NewFlagSet("mock", flag.ContinueOnError)
	out := fs.String("o", "", "write generated code to FILE instead of stdout")
	_ = fs.Parse(args)
	rest := fs.Args()
	if len(rest) == 0 {
		return fmt.Errorf("usage: ceedless mock [-o FILE] <header.h>")
	}
	hdr := rest[0]
	data, err := os.ReadFile(hdr)
	if err != nil {
		return err
	}

	var b strings.Builder
	fmt.Fprintf(&b, "/* SPDX-License-Identifier: MIT\n")
	fmt.Fprintf(&b, " * Generated by `ceedless mock %s` — edit freely.\n */\n", filepath.Base(hdr))
	fmt.Fprintf(&b, "#include \"ceedless/mock.h\"\n#include \"%s\"\n\n", filepath.Base(hdr))

	n := 0
	for _, m := range reFuncDecl.FindAllStringSubmatch(string(data), -1) {
		ret := strings.TrimSpace(m[1])
		name := m[2]
		params := strings.TrimSpace(m[3])
		if params == "" {
			params = "void"
		}
		if skipDecl(ret, name) {
			continue
		}
		fmt.Fprintf(&b, "MOCK_DEFINE(%s, %s, (%s))\n", name, ret, params)
		n++
	}
	if n == 0 {
		warn("no function declarations matched in %s", hdr)
	}

	if *out != "" {
		if err := os.WriteFile(*out, []byte(b.String()), 0o644); err != nil {
			return err
		}
		info("wrote %d mock(s) to %s", n, *out)
		return nil
	}
	_, err = os.Stdout.WriteString(b.String())
	return err
}

func skipDecl(ret, name string) bool {
	switch ret {
	case "", "typedef", "struct", "union", "enum":
		return true
	}
	switch name {
	case "if", "for", "while", "switch", "return", "sizeof":
		return true
	}
	return false
}

// shared shell helpers used by doctor/init/etc.

func lookPath(name string) (string, error) { return exec.LookPath(name) }

func captureOutput(name string, args ...string) (string, error) {
	out, err := exec.Command(name, args...).CombinedOutput()
	return string(out), err
}
