// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tevfik — https://github.com/tevfik/ceedless
package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// coreSources returns the absolute paths of all framework C sources.
func coreSources(home string) []string {
	rel := []string{
		"src/runner.c",
		"src/exception.c",
		"src/mock.c",
		"src/virtual_peripheral.c",
		"src/trace/trace_port.c",
		"src/trace/trace_host.c",
		"src/trace/trace_uart.c",
		"src/trace/trace_rtt.c",
		"src/trace/trace_itm.c",
		"src/trace/trace_buffer.c",
		"src/peripherals/vp_spi.c",
		"src/peripherals/vp_uart.c",
		"src/peripherals/vp_gpio.c",
		"src/peripherals/vp_adc.c",
	}
	out := make([]string, 0, len(rel))
	for _, r := range rel {
		p := filepath.Join(home, r)
		if exists(p) {
			out = append(out, p)
		}
	}
	return out
}

// DiscoverTests returns all test_*.c files under cfg.TestDirs, sorted.
func DiscoverTests(cfg *Config, filter string) ([]string, error) {
	var tests []string
	for _, d := range cfg.TestDirs {
		if !exists(d) {
			continue
		}
		err := filepath.Walk(d, func(p string, fi os.FileInfo, err error) error {
			if err != nil || fi.IsDir() {
				return nil
			}
			b := filepath.Base(p)
			if !strings.HasPrefix(b, "test_") || !strings.HasSuffix(b, ".c") {
				return nil
			}
			if filter != "" && !strings.Contains(b, filter) {
				return nil
			}
			tests = append(tests, p)
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	sort.Strings(tests)
	return tests, nil
}

var (
	reTestFn   = regexp.MustCompile(`^\s*void\s+(test_[A-Za-z0-9_]+)\s*\(\s*void\s*\)`)
	reSrcAnnot = regexp.MustCompile(`TEST_SOURCE_FILE\s*\(\s*"([^"]+)"\s*\)`)
)

// ScanTest returns the list of test_* function names and TEST_SOURCE_FILE
// annotations found in a single test source file.
func ScanTest(path string) (tests, extras []string, err error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, nil, err
	}
	defer f.Close()
	seen := map[string]bool{}
	scan := bufio.NewScanner(f)
	scan.Buffer(make([]byte, 65536), 1<<20)
	for scan.Scan() {
		line := scan.Text()
		if m := reTestFn.FindStringSubmatch(line); m != nil {
			if !seen[m[1]] {
				seen[m[1]] = true
				tests = append(tests, m[1])
			}
		}
		for _, m := range reSrcAnnot.FindAllStringSubmatch(line, -1) {
			extras = append(extras, m[1])
		}
	}
	return tests, extras, scan.Err()
}

// SynthRunner writes a generated _runner.c containing main() and RUN_TEST
// calls for every test_* function found in srcTest.
func SynthRunner(srcTest, outPath string) error {
	tests, _, err := ScanTest(srcTest)
	if err != nil {
		return err
	}
	stem := strings.TrimSuffix(filepath.Base(srcTest), ".c")
	var b strings.Builder
	b.WriteString("/* AUTO-GENERATED BY ceedless — DO NOT EDIT */\n")
	b.WriteString("#include \"ceedless/ceedless.h\"\n")
	b.WriteString("#include <stdlib.h>\n\n")
	for _, t := range tests {
		fmt.Fprintf(&b, "void %s(void);\n", t)
	}
	b.WriteString("\nint main(void) {\n")
	fmt.Fprintf(&b, "    ceedless_begin(%q);\n", stem)
	b.WriteString("    const char *jx = getenv(\"CEEDLESS_JUNIT\");\n")
	b.WriteString("    if (jx) ceedless_set_junit_path(jx);\n")
	for _, t := range tests {
		fmt.Fprintf(&b, "    RUN_TEST(%s);\n", t)
	}
	b.WriteString("    return ceedless_end();\n}\n")
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		return err
	}
	return os.WriteFile(outPath, []byte(b.String()), 0o644)
}
